Pr8: fix critical bug in ToxLoadJniLibrary.scala
TokTok/jvm-toxcore-c pull request #13
Opened 2016-12-27 12:15 UTC by zoff99

* pin sources to specific version
* make perl scripts output all commands to /tmp/inst.log
* fix bug in src/main/java/im/tox/tox4j/impl/jni/ToxLoadJniLibrary.scala

2016-12-27 12:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/TokTok/jvm-toxcore-c?pullRequest=13) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/TokTok/jvm-toxcore-c?pullRequest=13) before we can accept your contribution.<br/>

2016-12-28 20:04 UTC, iphydf requested changes
Can you make a separate PR for the version pinning stuff? Also, don't use "request review" - just assign the PR to me.

2016-12-28 20:34 UTC, iphydf commented
I'll make a version pinning PR.

2016-12-29 07:21 UTC, zoff99 commented
will split up

2016-12-29 07:21 UTC, closed without merging